### ISSUE TITLE
What is the answer to the forum's security question?

### ISSUE THREAD

**Issue by pklloveyou** [ProjectSkyfire/SkyFire_548#865]
What is the answer to the forum's security question?
https://www.projectskyfire.org/
Unable to register
![TIM截图20190721131142](https://user-images.githubusercontent.com/18535853/61587259-28018b00-abb9-11e9-9dc7-2bf55a428ef4.jpg)

**Comment by SkyFire** [comment]
Should be fixed now. Try again

**Comment by pklloveyou** [comment]
![TIM截图20190721131142](https://user-images.githubusercontent.com/18535853/61598936-61d49f00-ac56-11e9-8339-4112ae388890.jpg)
@SkyFire :( Still can't register

**Comment by SkyFire** [comment]
I have had 5 people register today. If you are trying to use a proxy it will not allow you to register. What country are you in?

**Comment by pklloveyou** [comment]
@SkyFire I am in China. CAPTCHA .... o.O .. I try with VPN

**Comment by pklloveyou** [comment]
thank you very much。。I try again
